apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h62c471l7-go
  janus-idp.io/tekton: h62c471l7-go
  backstage.io/kubernetes-id: h62c471l7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h62c471l7-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
